version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy

hooks:
  BeforeInstall:
    - location: scripts/stop_old_containers.sh
      timeout: 100
      runas: ec2-user
      log: /var/log/codedeploy/before_install.log

  AfterInstall:
    - location: scripts/start_new_containers.sh
      timeout: 100
      runas: ec2-user
      log: /var/log/codedeploy/after_install.log
