name: Update API URL to Env

on:
  workflow_dispatch:
    inputs:
      backend_elb_url:
        description: "Backend ELB URL"
        required: true

jobs:
  update-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update .env file
        run: |
          # 기존 .env 파일이 없다면 생성
          touch .env

          # 기존 .env 파일 백업
          cp .env .env.bak

          # 기존 .env 파일에서 REACT_APP_BACKEND_API 값 변경 (없으면 추가)
          if grep -q "REACT_APP_BACKEND_API=" .env; then
            sed -i "s|REACT_APP_BACKEND_API=.*|REACT_APP_BACKEND_API=${{ github.event.inputs.backend_elb_url }}|g" .env
          else
            echo "REACT_APP_BACKEND_API=${{ github.event.inputs.backend_elb_url }}" >> .env
          fi

          # 변경된 .env 파일 확인
          cat .env

    #   - name: Commit and push updated .env file
    #     run: |
    #       git config --global user.email "github-actions@github.com"
    #       git config --global user.name "GitHub Actions"
    #       git add .env
    #       git commit -m "Update REACT_APP_BACKEND_API in .env"
    #       git push origin main
